src/Entity/Invitation.php
<?php declare(strict_types = 1);

namespace App\Entity;

use DateTimeImmutable;
use Doctrine\ORM\Mapping as ORM;
use Ramsey\Uuid\Uuid;

/**
 * @ORM\Entity()
 * @ORM\Table(name="app_invite")
 */
class Invitation
{
    /**
     * @ORM\Id()
     * @ORM\Column(type="uuid")
     */
    private $inviteCode;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", cascade={"all"})
     * @ORM\JoinColumn(name="owner_id", nullable=false)
     */
    private $owner;

    /**
     * @ORM\Column(type="datetime_immutable", nullable=true)
     */
    private $redeemedAt;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $redeemedBy;

    public function __construct(User $owner)
    {
        $this->inviteCode = Uuid::uuid4();
        $this->owner = $owner;
    }

    public function redeem(User $invitee): void
    {
        $this->redeemedAt = new DateTimeImmutable();
        $this->redeemedBy = $invitee->getEmail();
    }

    public function getInviteCode(): string
    {
        return $this->inviteCode->toString();
    }

    public function getOwner(): User
    {
        return $this->owner;
    }

    public function isRedeemed(): bool
    {
        return $this->redeemedAt !== null;
    }

    public function __toString(): string
    {
        return $this->getInviteCode();
    }
}

src/Entity/User.php
<?php declare(strict_types = 1);

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity()
 * @ORM\Table(name="app_user")
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(unique=true)
     */
    private $email;

    /**
     * @ORM\Column(name="password", length=100)
     */
    private $encodedPassword = '';

    public function __construct(string $email)
    {
        $this->email = $email;
    }

    public function getId(): int
    {
        return $this->id;
    }

    public function updatePassword(string $encodedPassword): void
    {
        $this->encodedPassword = $encodedPassword;
    }

    public function getEmail(): string
    {
        return $this->email;
    }

    public function getUsername(): string
    {
        return $this->getEmail();
    }

    public function getPassword(): string
    {
        return $this->encodedPassword;
    }

    public function getRoles(): array
    {
        return ['ROLE_USER'];
    }

    public function getSalt(): ?string
    {
        return null;
    }

    public function eraseCredentials(): void
    {
    }

    public function __toString(): string
    {
        return $this->getEmail();
    }
}

src/Form/RegistrationType.php
<?php declare(strict_types = 1);

namespace App\Form;

use App\Message\RegisterUser;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class RegistrationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add(
                'inviteCode',
                TextType::class,
                [
                    'label' => 'Invite code:',
                    'required' => true,
                ]
            )
            ->add(
                'email',
                EmailType::class,
                [
                    'label' => 'Email:',
                    'required' => true,
                ]
            )
            ->add(
                'plainPassword',
                PasswordType::class,
                [
                    'label' => 'Password:',
                    'required' => true,
                ]
            )
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefault('data_class', RegisterUser::class);
    }
}

src/Controller/DashboardController.php
<?php declare(strict_types = 1);

namespace App\Controller;

use App\Registration\InvitationProvider;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class DashboardController extends AbstractController
{
    private $invitationProvider;

    public function __construct(InvitationProvider $invitationProvider)
    {
        $this->invitationProvider = $invitationProvider;
    }

    /**
     * @IsGranted("ROLE_USER")
     * @Route(path="/", name="dashboard")
     */
    public function index()
    {
        return $this->render(
            'dashboard.html.twig',
            [
                'invitations' => $this->invitationProvider->getInvitations($this->getUser()),
            ]
        );
    }
}

src/Controller/SecurityController.php
<?php declare(strict_types = 1);

namespace App\Controller;

use App\Form\RegistrationType;
use App\Registration\Exceptions\EmailAlreadyRegisteredException;
use App\Registration\Exceptions\InvalidInvitationException;
use App\Registration\Exceptions\RegistrationFailedException;
use RuntimeException;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\FormError;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Messenger\MessageBusInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;

class SecurityController extends AbstractController
{
    /**
     * @Route(path="/login", name="login")
     */
    public function login(AuthenticationUtils $authUtils)
    {
        return $this->render(
            'login.html.twig',
            [
                'error' => $authUtils->getLastAuthenticationError(),
                'last_username' => $authUtils->getLastUsername(),
            ]
        );
    }

    /**
     * @Route(path="/register", name="register")
     */
    public function register(Request $request, MessageBusInterface $messageBus)
    {
        $form = $this->createForm(RegistrationType::class);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            try {
                $messageBus->dispatch($form->getData());
            } catch (EmailAlreadyRegisteredException $exception) {
                $form->get('email')->addError(new FormError($exception->getMessage()));

                return $this->render(
                    'register.html.twig',
                    [
                        'form' => $form->createView(),
                    ]
                );
            } catch (InvalidInvitationException $exception) {
                $form->get('inviteCode')->addError(new FormError($exception->getMessage()));

                return $this->render(
                    'register.html.twig',
                    [
                        'form' => $form->createView(),
                    ]
                );
            }

            return $this->redirectToRoute('login');
        }

        return $this->render(
            'register.html.twig',
            [
                'form' => $form->createView(),
            ]
        );
    }

    /**
     * @Route(path="/logout", name="logout")
     */
    public function logout()
    {
        throw new RuntimeException('This route will be handled by Symfony\'s security system.');
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <title>{% block title %}Messenger Demo: Registration with invite code{% endblock %}</title>
    </head>
    <body>
        <div class="container mt-md-3">
            {% block body %}{% endblock %}
        </div>
    </body>
</html>

templates/dashboard.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <h1>Your invite codes</h1>

    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Invite code</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            {% for invitation in invitations %}
            <tr>
                <td><code>{{ invitation }}</code></td>
                <td>
                    {% if invitation.redeemed %}
                        <span class="badge badge-success">redeemed</span>
                    {% else %}
                        <span class="badge badge-primary">open</span>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

{% endblock %}

templates/login.html.twig
{% extends 'base.html.twig' %}


{% block body %}

    <h1>Login</h1>

    {% if error %}
    <div class="alert alert-danger">
        <strong>Login failed</strong> {{ error.messageKey|trans(error.messageData, "security") }}
    </div>
    {% endif %}

    <form action="{{ path('login') }}" method="post">
        <div class="mb-3">
            <label for="username">Email:</label>
            <input type="text" id="username" name="_username" value="{{ last_username }}" class="form-control" />
        </div>

        <div class="mb-3">
            <label for="password">Password:</label>
            <input type="password" id="password" name="_password" class="form-control" />
        </div>

        <div class="mb-3">
            <button type="submit" class="btn btn-primary">login</button>&emsp;
            <span class="text-muted">No account yet? <a href="{{ path('register') }}">You can register with an invite code.</a></span>
        </div>
    </form>

{% endblock %}

templates/register.html.twig
{% extends 'base.html.twig' %}


{% block body %}

    <h1>Register a new account</h1>

    {{ form_start(form) }}
        {{ form_errors(form) }}

        {{ form_row(form.inviteCode) }}
        {{ form_row(form.email) }}
        {{ form_row(form.plainPassword) }}

        <div class="mb-3">
            <button type="submit" class="btn btn-primary">register</button>&emsp;
            <a href="{{ path('login') }}">back to login</a>
        </div>
    {{ form_end(form) }}

{% endblock %}